#!/bin/sh
# Copyright 2025 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
# Copyright 2024 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
# Copyright 2023 (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
#
#
# Licensed under (Holloway) Chew, Kean Ho's Liberal License (the 'License').
# You must comply with the license to use the content. Get the License at:
#
# https://doi.org/10.5281/zenodo.13770769
#
# You MUST ensure any interaction with the content STRICTLY COMPLIES with
# the permissions and limitations set forth in the license.




# define all destination paths
UNICODES_DEST_C="${PROJECT_PATH_OUTPUT}/C/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_C="${UNICODES_DEST_C}/${UNICODES_FILENAME_LOWERCASE}.c"
UNICODES_DEST_TITLECASE_C="${UNICODES_DEST_C}/${UNICODES_FILENAME_TITLECASE}.c"
UNICODES_DEST_UPPERCASE_C="${UNICODES_DEST_C}/${UNICODES_FILENAME_UPPERCASE}.c"




UNICODES_DEST_GO="${PROJECT_PATH_OUTPUT}/Go/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_GO="${UNICODES_DEST_GO}/${UNICODES_FILENAME_LOWERCASE}.go"
UNICODES_DEST_TITLECASE_GO="${UNICODES_DEST_GO}/${UNICODES_FILENAME_TITLECASE}.go"
UNICODES_DEST_UPPERCASE_GO="${UNICODES_DEST_GO}/${UNICODES_FILENAME_UPPERCASE}.go"




UNICODES_DEST_NIM="${PROJECT_PATH_OUTPUT}/Nim/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_NIM="${UNICODES_DEST_NIM}/${UNICODES_FILENAME_LOWERCASE}.nim"
UNICODES_DEST_TITLECASE_NIM="${UNICODES_DEST_NIM}/${UNICODES_FILENAME_TITLECASE}.nim"
UNICODES_DEST_UPPERCASE_NIM="${UNICODES_DEST_NIM}/${UNICODES_FILENAME_UPPERCASE}.nim"




UNICODES_DEST_POWERSHELL="${PROJECT_PATH_OUTPUT}/PowerShell/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_POWERSHELL="${UNICODES_DEST_POWERSHELL}/${UNICODES_FILENAME_LOWERCASE}.ps1"
UNICODES_DEST_TITLECASE_POWERSHELL="${UNICODES_DEST_POWERSHELL}/${UNICODES_FILENAME_TITLECASE}.ps1"
UNICODES_DEST_UPPERCASE_POWERSHELL="${UNICODES_DEST_POWERSHELL}/${UNICODES_FILENAME_UPPERCASE}.ps1"




UNICODES_DEST_PYTHON="${PROJECT_PATH_OUTPUT}/Python/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_PYTHON="${UNICODES_DEST_PYTHON}/${UNICODES_FILENAME_UNDERSCORE_LOWERCASE}.py"
UNICODES_DEST_TITLECASE_PYTHON="${UNICODES_DEST_PYTHON}/${UNICODES_FILENAME_UNDERSCORE_TITLECASE}.py"
UNICODES_DEST_UPPERCASE_PYTHON="${UNICODES_DEST_PYTHON}/${UNICODES_FILENAME_UNDERSCORE_UPPERCASE}.py"




UNICODES_DEST_RUST="${PROJECT_PATH_OUTPUT}/Rust/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_RUST="${UNICODES_DEST_RUST}/${UNICODES_FILENAME_UNDERSCORE_LOWERCASE}.rs"
UNICODES_DEST_TITLECASE_RUST="${UNICODES_DEST_RUST}/${UNICODES_FILENAME_UNDERSCORE_TITLECASE}.rs"
UNICODES_DEST_UPPERCASE_RUST="${UNICODES_DEST_RUST}/${UNICODES_FILENAME_UNDERSCORE_UPPERCASE}.rs"




UNICODES_DEST_SHELL="${PROJECT_PATH_OUTPUT}/Shell/${UNICODES_DIRECTORY%/}"
UNICODES_DEST_LOWERCASE_SHELL="${UNICODES_DEST_SHELL}/${UNICODES_FILENAME_LOWERCASE}.sh"
UNICODES_DEST_TITLECASE_SHELL="${UNICODES_DEST_SHELL}/${UNICODES_FILENAME_TITLECASE}.sh"
UNICODES_DEST_UPPERCASE_SHELL="${UNICODES_DEST_SHELL}/${UNICODES_FILENAME_UPPERCASE}.sh"




# report status
return 0
