// Copyright 2025 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
// Copyright 2024 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
// Copyright 2023 (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
//
//
// Licensed under (Holloway) Chew, Kean Ho's Liberal License (the 'License').
// You must comply with the license to use the content. Get the License at:
//
// https://doi.org/10.5281/zenodo.13770769
//
// You MUST ensure any interaction with the content STRICTLY COMPLIES with
// the permissions and limitations set forth in the license.


// WARNING: This file is AUTO-GENERATED! DO NOT EDIT!
// WARNING: Consult Copyright owners or documentations.

pub type Signal = uint16;




// Signals' ID
// commonly used
pub const HESTIASIGNALS_OK: Signal = 0;
pub const HESTIASIGNALS_BAD_EXEC: Signal = 1;
pub const HESTIASIGNALS_BAD_BUSY: Signal = 2;
pub const HESTIASIGNALS_BAD_DESCRIPTOR: Signal = 3;
pub const HESTIASIGNALS_BAD_EXCHANGE: Signal = 4;
pub const HESTIASIGNALS_BAD_MOUNT: Signal = 5;
pub const HESTIASIGNALS_BAD_PIPE: Signal = 6;
pub const HESTIASIGNALS_BAD_REQUEST: Signal = 7;
pub const HESTIASIGNALS_BAD_STREAM_PIPE: Signal = 8;
pub const HESTIASIGNALS_PROCESS_IS_DEAD: Signal = 9;
pub const HESTIASIGNALS_CANCELLED: Signal = 10;
pub const HESTIASIGNALS_CLEANING_REQUIRED: Signal = 11;
pub const HESTIASIGNALS_DEADLOCK: Signal = 12;
pub const HESTIASIGNALS_EXPIRED: Signal = 13;
pub const HESTIASIGNALS_ILLEGAL_BYTE_SEQUENCE: Signal = 14;
pub const HESTIASIGNALS_ILLEGAL_SEEK: Signal = 15;
pub const HESTIASIGNALS_INVALID_ARGUMENT: Signal = 16;
pub const HESTIASIGNALS_IS_EMPTY: Signal = 17;
pub const HESTIASIGNALS_MAXED_EXCHANGE: Signal = 18;
pub const HESTIASIGNALS_MAXED_QUOTA: Signal = 19;
pub const HESTIASIGNALS_MISSING_LOCK: Signal = 20;
pub const HESTIASIGNALS_IS_NOT_EMPTY: Signal = 21;
pub const HESTIASIGNALS_NOT_PERMITTED: Signal = 22;
pub const HESTIASIGNALS_NOT_POSSIBLE: Signal = 23;
pub const HESTIASIGNALS_NOT_POSSIBLE_BY_RFKILL: Signal = 24;
pub const HESTIASIGNALS_NOT_RECOVERABLE: Signal = 25;
pub const HESTIASIGNALS_OUT_OF_RANGE: Signal = 26;
pub const HESTIASIGNALS_PERMISSION_DENIED: Signal = 27;
pub const HESTIASIGNALS_TIMEOUT: Signal = 28;
pub const HESTIASIGNALS_TOO_MANY_READ: Signal = 29;
pub const HESTIASIGNALS_TOO_MANY_LOOP: Signal = 30;
pub const HESTIASIGNALS_TOO_MANY_REFERENCES: Signal = 31;
pub const HESTIASIGNALS_TOO_MANY_LINK: Signal = 32;
pub const HESTIASIGNALS_TOO_MANY_OPENED: Signal = 33;
pub const HESTIASIGNALS_TRY_AGAIN: Signal = 34;
pub const HESTIASIGNALS_UNSUPPORTED: Signal = 35;
pub const HESTIASIGNALS_WOULD_BLOCK: Signal = 36;




// lifecycle states
pub const HESTIASIGNALS_RESTART: Signal = 37;
pub const HESTIASIGNALS_RESUME: Signal = 38;
pub const HESTIASIGNALS_SHUTDOWN: Signal = 39;
pub const HESTIASIGNALS_SLEEP: Signal = 40;
pub const HESTIASIGNALS_STALLED: Signal = 41;
pub const HESTIASIGNALS_STANDBY: Signal = 42;
pub const HESTIASIGNALS_UNRESPONSIVE: Signal = 43;
pub const HESTIASIGNALS_TERMINATE: Signal = 44;
pub const HESTIASIGNALS_PROGRESS_SCHEDULED: Signal = 45;
pub const HESTIASIGNALS_PROGRESS_ALREADY_EXECUTING: Signal = 46;
pub const HESTIASIGNALS_PROGRESS_EXECUTING: Signal = 47;
pub const HESTIASIGNALS_PROGRESS_COMPLETED: Signal = 48;
pub const HESTIASIGNALS_PROGRESS_UNRESPONSIVE: Signal = 49;
pub const HESTIASIGNALS_PROGRESS_TERMINATE: Signal = 50;




// tri-tiers intercommunications
pub const HESTIASIGNALS_LV1_NOT_SYNC: Signal = 51;
pub const HESTIASIGNALS_LV1_PAUSED: Signal = 52;
pub const HESTIASIGNALS_LV1_RESET: Signal = 53;
pub const HESTIASIGNALS_LV2_NOT_SYNC: Signal = 54;
pub const HESTIASIGNALS_LV2_PAUSED: Signal = 55;
pub const HESTIASIGNALS_LV2_RESET: Signal = 56;
pub const HESTIASIGNALS_LV3_NOT_SYNC: Signal = 57;
pub const HESTIASIGNALS_LV3_PAUSED: Signal = 58;
pub const HESTIASIGNALS_LV3_RESET: Signal = 59;




// data (input/output parameters type etc)
pub const HESTIASIGNALS_DATA_BAD: Signal = 60;
pub const HESTIASIGNALS_DATA_EMPTY: Signal = 61;
pub const HESTIASIGNALS_DATA_INVALID: Signal = 62;
pub const HESTIASIGNALS_DATA_IS_UNIQUE: Signal = 63;
pub const HESTIASIGNALS_DATA_IS_NOT_UNIQUE: Signal = 64;
pub const HESTIASIGNALS_DATA_BUSY: Signal = 65;
pub const HESTIASIGNALS_DATA_DEAD: Signal = 66;
pub const HESTIASIGNALS_DATA_EXISTS: Signal = 67;
pub const HESTIASIGNALS_DATA_FAULTY: Signal = 68;
pub const HESTIASIGNALS_DATA_MISSING: Signal = 69;
pub const HESTIASIGNALS_DATA_OVERFLOW: Signal = 70;
pub const HESTIASIGNALS_DATA_POISONED: Signal = 71;
pub const HESTIASIGNALS_DATA_REMOVED: Signal = 72;
pub const HESTIASIGNALS_DATA_TOO_BIG: Signal = 73;
pub const HESTIASIGNALS_DATA_TOO_MANY_OPENED: Signal = 74;
pub const HESTIASIGNALS_DATA_TOO_LONG: Signal = 75;
pub const HESTIASIGNALS_DATA_MISMATCHED: Signal = 76;
pub const HESTIASIGNALS_DATA_IS_NOT_DIRECTORY: Signal = 77;
pub const HESTIASIGNALS_DATA_IS_NOT_FILE: Signal = 78;
pub const HESTIASIGNALS_DATA_IS_NOT_LINK: Signal = 79;
pub const HESTIASIGNALS_DATA_IS_NOT_SOCKET: Signal = 80;
pub const HESTIASIGNALS_DATA_REMOTE_CHANGED: Signal = 81;
pub const HESTIASIGNALS_DATA_REMOTE_ERROR: Signal = 82;
pub const HESTIASIGNALS_DATA_REMOTE_IO: Signal = 83;
pub const HESTIASIGNALS_DATA_MISSING_STREAMABLE_RESOURCES: Signal = 84;
pub const HESTIASIGNALS_DATA_NOT_STREAMABLE: Signal = 85;




// entity (device file directory object etc)
pub const HESTIASIGNALS_ENTITY_BAD: Signal = 86;
pub const HESTIASIGNALS_ENTITY_EMPTY: Signal = 87;
pub const HESTIASIGNALS_ENTITY_INVALID: Signal = 88;
pub const HESTIASIGNALS_ENTITY_IS_UNIQUE: Signal = 89;
pub const HESTIASIGNALS_ENTITY_IS_NOT_UNIQUE: Signal = 90;
pub const HESTIASIGNALS_ENTITY_BUSY: Signal = 91;
pub const HESTIASIGNALS_ENTITY_DEAD: Signal = 92;
pub const HESTIASIGNALS_ENTITY_EXISTS: Signal = 93;
pub const HESTIASIGNALS_ENTITY_FAULTY: Signal = 94;
pub const HESTIASIGNALS_ENTITY_MISSING: Signal = 95;
pub const HESTIASIGNALS_ENTITY_MISSING_CHILD: Signal = 96;
pub const HESTIASIGNALS_ENTITY_OUT_OF_BUFFER: Signal = 97;
pub const HESTIASIGNALS_ENTITY_POISONED: Signal = 98;
pub const HESTIASIGNALS_ENTITY_REMOVED: Signal = 99;
pub const HESTIASIGNALS_ENTITY_TOO_BIG: Signal = 100;
pub const HESTIASIGNALS_ENTITY_TOO_MANY_OPENED: Signal = 101;
pub const HESTIASIGNALS_ENTITY_UNATTACHED: Signal = 102;
pub const HESTIASIGNALS_ENTITY_MISMATCHED: Signal = 103;
pub const HESTIASIGNALS_ENTITY_IS_NOT_DIRECTORY: Signal = 104;
pub const HESTIASIGNALS_ENTITY_IS_NOT_FILE: Signal = 105;
pub const HESTIASIGNALS_ENTITY_IS_NOT_LINK: Signal = 106;
pub const HESTIASIGNALS_ENTITY_IS_NOT_SOCKET: Signal = 107;
pub const HESTIASIGNALS_ENTITY_REMOTE_CHANGED: Signal = 108;
pub const HESTIASIGNALS_ENTITY_REMOTE_ERROR: Signal = 109;
pub const HESTIASIGNALS_ENTITY_REMOTE_IO: Signal = 110;
pub const HESTIASIGNALS_ENTITY_MISSING_STREAMABLE_RESOURCES: Signal = 111;
pub const HESTIASIGNALS_ENTITY_NOT_STREAMABLE: Signal = 112;
pub const HESTIASIGNALS_ENTITY_STREAMABLE: Signal = 113;
pub const HESTIASIGNALS_ENTITY_A_TYPEWRITER: Signal = 114;
pub const HESTIASIGNALS_ENTITY_NOT_A_TYPEWRITER: Signal = 115;
pub const HESTIASIGNALS_ENTITY_BAD_DESCRIPTOR: Signal = 116;
pub const HESTIASIGNALS_ENTITY_FILETABLE_OVERFLOW: Signal = 117;




// key (cryptography)
pub const HESTIASIGNALS_KEY_BAD: Signal = 118;
pub const HESTIASIGNALS_KEY_DESTROYED: Signal = 119;
pub const HESTIASIGNALS_KEY_EXPIRED: Signal = 120;
pub const HESTIASIGNALS_KEY_MISSING: Signal = 121;
pub const HESTIASIGNALS_KEY_REJECTED: Signal = 122;
pub const HESTIASIGNALS_KEY_REVOKED: Signal = 123;




// library
pub const HESTIASIGNALS_LIBRARY_BAD: Signal = 124;
pub const HESTIASIGNALS_LIBRARY_CORRUPTED: Signal = 125;
pub const HESTIASIGNALS_LIBRARY_EXEC_FAILED: Signal = 126;
pub const HESTIASIGNALS_LIBRARY_MAXED: Signal = 127;
pub const HESTIASIGNALS_LIBRARY_MISSING: Signal = 128;




// network
pub const HESTIASIGNALS_NETWORK_BAD: Signal = 129;
pub const HESTIASIGNALS_NETWORK_BAD_AD: Signal = 130;
pub const HESTIASIGNALS_NETWORK_DOWN: Signal = 131;
pub const HESTIASIGNALS_NETWORK_NOT_CONNECTED: Signal = 132;
pub const HESTIASIGNALS_NETWORK_RESET: Signal = 133;
pub const HESTIASIGNALS_NETWORK_RFS: Signal = 134;
pub const HESTIASIGNALS_NETWORK_UNREACHABLE: Signal = 135;

pub const HESTIASIGNALS_NETWORK_HOST_DOWN: Signal = 136;
pub const HESTIASIGNALS_NETWORK_HOST_UNREACHABLE: Signal = 137;
pub const HESTIASIGNALS_NETWORK_SOCKET_UNSUPPORTED: Signal = 138;

pub const HESTIASIGNALS_NETWORK_ADDRESS_IN_USE: Signal = 139;
pub const HESTIASIGNALS_NETWORK_ADDRESS_UNAVAILABLE: Signal = 140;

pub const HESTIASIGNALS_NETWORK_CONN_ABORTED: Signal = 141;
pub const HESTIASIGNALS_NETWORK_CONN_IS_CONNECTED: Signal = 142;
pub const HESTIASIGNALS_NETWORK_CONN_MISSING_DEST_ADDRESS: Signal = 143;
pub const HESTIASIGNALS_NETWORK_CONN_MULTIHOP: Signal = 144;
pub const HESTIASIGNALS_NETWORK_CONN_NOT_CONNECTED: Signal = 145;
pub const HESTIASIGNALS_NETWORK_CONN_REFUSED: Signal = 146;
pub const HESTIASIGNALS_NETWORK_CONN_RESET: Signal = 147;

pub const HESTIASIGNALS_NETWORK_PAYLOAD_BAD: Signal = 148;
pub const HESTIASIGNALS_NETWORK_PAYLOAD_EMPTY: Signal = 149;
pub const HESTIASIGNALS_NETWORK_PAYLOAD_MISSING: Signal = 150;
pub const HESTIASIGNALS_NETWORK_PAYLOAD_TOO_LONG: Signal = 151;




// protocol
pub const HESTIASIGNALS_PROTOCOL_ADDRESS_UNSUPPORTED: Signal = 152;
pub const HESTIASIGNALS_PROTOCOL_BAD: Signal = 153;
pub const HESTIASIGNALS_PROTOCOL_FAMILY_UNSUPPORTED: Signal = 154;
pub const HESTIASIGNALS_PROTOCOL_MISSING: Signal = 155;
pub const HESTIASIGNALS_PROTOCOL_INVALID: Signal = 156;
pub const HESTIASIGNALS_PROTOCOL_FAULTY: Signal = 157;
pub const HESTIASIGNALS_PROTOCOL_EMPTY: Signal = 158;
pub const HESTIASIGNALS_PROTOCOL_UNSUPPORTED: Signal = 159;




// system (e.g. os interactable system)
pub const HESTIASIGNALS_SYSTEM_BAD_IO: Signal = 160;
pub const HESTIASIGNALS_SYSTEM_DEVICE_CROSS_LINK: Signal = 161;
pub const HESTIASIGNALS_SYSTEM_INTERRUPT_CALL: Signal = 162;
pub const HESTIASIGNALS_SYSTEM_INVALID: Signal = 163;
pub const HESTIASIGNALS_SYSTEM_MISSING_BLOCK_DEVICE: Signal = 164;
pub const HESTIASIGNALS_SYSTEM_MISSING_DEVICE: Signal = 165;
pub const HESTIASIGNALS_SYSTEM_MISSING_IO: Signal = 166;
pub const HESTIASIGNALS_SYSTEM_MISSING_PROCESS: Signal = 167;
pub const HESTIASIGNALS_SYSTEM_OUT_OF_DOMAIN: Signal = 168;
pub const HESTIASIGNALS_SYSTEM_OUT_OF_MEMORY: Signal = 169;
pub const HESTIASIGNALS_SYSTEM_OUT_OF_SPACE: Signal = 170;
pub const HESTIASIGNALS_SYSTEM_READ_ONLY_FILESYSTEM: Signal = 171;




// user
pub const HESTIASIGNALS_USER_ACCESS_BANNED: Signal = 172;
pub const HESTIASIGNALS_USER_ACCESS_LOCKED: Signal = 173;
pub const HESTIASIGNALS_USER_ACCESS_NOT_VERIFIED: Signal = 174;
pub const HESTIASIGNALS_USER_ACCESS_BAD: Signal = 175;
pub const HESTIASIGNALS_USER_ACCESS_REJECTED: Signal = 176;
pub const HESTIASIGNALS_USER_ACCESS_REVOKED: Signal = 177;
pub const HESTIASIGNALS_USER_ACCESS_EXISTS: Signal = 178;
pub const HESTIASIGNALS_USER_ACCESS_EMPTY: Signal = 179;
pub const HESTIASIGNALS_USER_ACCESS_MISSING: Signal = 180;
pub const HESTIASIGNALS_USER_ACCESS_INVALID: Signal = 181;
pub const HESTIASIGNALS_USER_ACCESS_EXPIRED: Signal = 182;
pub const HESTIASIGNALS_USER_ACCESS_MISMATCHED: Signal = 183;

pub const HESTIASIGNALS_USER_MFA_BANNED: Signal = 184;
pub const HESTIASIGNALS_USER_MFA_LOCKED: Signal = 185;
pub const HESTIASIGNALS_USER_MFA_NOT_VERIFIED: Signal = 186;
pub const HESTIASIGNALS_USER_MFA_BAD: Signal = 187;
pub const HESTIASIGNALS_USER_MFA_REJECTED: Signal = 188;
pub const HESTIASIGNALS_USER_MFA_REVOKED: Signal = 189;
pub const HESTIASIGNALS_USER_MFA_EXISTS: Signal = 190;
pub const HESTIASIGNALS_USER_MFA_EMPTY: Signal = 191;
pub const HESTIASIGNALS_USER_MFA_MISSING: Signal = 192;
pub const HESTIASIGNALS_USER_MFA_INVALID: Signal = 193;
pub const HESTIASIGNALS_USER_MFA_EXPIRED: Signal = 194;
pub const HESTIASIGNALS_USER_MFA_MISMATCHED: Signal = 195;

pub const HESTIASIGNALS_USER_ID_EXISTS: Signal = 196;
pub const HESTIASIGNALS_USER_ID_BANNED: Signal = 197;
pub const HESTIASIGNALS_USER_ID_BAD: Signal = 198;
pub const HESTIASIGNALS_USER_ID_LOCKED: Signal = 199;
pub const HESTIASIGNALS_USER_ID_NOT_VERIFIED: Signal = 200;
pub const HESTIASIGNALS_USER_ID_EMPTY: Signal = 201;
pub const HESTIASIGNALS_USER_ID_MISSING: Signal = 202;
pub const HESTIASIGNALS_USER_ID_INVALID: Signal = 203;
pub const HESTIASIGNALS_USER_ID_EXPIRED: Signal = 204;
pub const HESTIASIGNALS_USER_ID_MISMATCHED: Signal = 205;
pub const HESTIASIGNALS_USER_ID_DELETED: Signal = 206;

pub const HESTIASIGNALS_USER_PASSWORD_EXISTS: Signal = 207;
pub const HESTIASIGNALS_USER_PASSWORD_BANNED: Signal = 208;
pub const HESTIASIGNALS_USER_PASSWORD_BAD: Signal = 209;
pub const HESTIASIGNALS_USER_PASSWORD_REJECTED: Signal = 210;
pub const HESTIASIGNALS_USER_PASSWORD_REVOKED: Signal = 211;
pub const HESTIASIGNALS_USER_PASSWORD_EMPTY: Signal = 212;
pub const HESTIASIGNALS_USER_PASSWORD_MISSING: Signal = 213;
pub const HESTIASIGNALS_USER_PASSWORD_INVALID: Signal = 214;
pub const HESTIASIGNALS_USER_PASSWORD_EXPIRED: Signal = 215;
pub const HESTIASIGNALS_USER_PASSWORD_MISMATCHED: Signal = 216;

pub const HESTIASIGNALS_USER_KEY_EXISTS: Signal = 217;
pub const HESTIASIGNALS_USER_KEY_BANNED: Signal = 218;
pub const HESTIASIGNALS_USER_KEY_BAD: Signal = 219;
pub const HESTIASIGNALS_USER_KEY_REJECTED: Signal = 220;
pub const HESTIASIGNALS_USER_KEY_REVOKED: Signal = 221;
pub const HESTIASIGNALS_USER_KEY_EMPTY: Signal = 222;
pub const HESTIASIGNALS_USER_KEY_MISSING: Signal = 223;
pub const HESTIASIGNALS_USER_KEY_INVALID: Signal = 224;
pub const HESTIASIGNALS_USER_KEY_EXPIRED: Signal = 225;
pub const HESTIASIGNALS_USER_KEY_MISMATCHED: Signal = 226;
