// Copyright 2025 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
// Copyright 2024 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
// Copyright 2023 (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
//
//
// Licensed under (Holloway) Chew, Kean Ho's Liberal License (the 'License').
// You must comply with the license to use the content. Get the License at:
//
// https://doi.org/10.5281/zenodo.13770769
//
// You MUST ensure any interaction with the content STRICTLY COMPLIES with
// the permissions and limitations set forth in the license.


// WARNING: This file is AUTO-GENERATED! DO NOT EDIT!
// WARNING: Consult Copyright owners or documentations.

#ifndef HestiaSIGNALS_CODES
#define HestiaSIGNALS_CODES

#include "../HestiaNUMBERS/Data.h"

typedef HestiaSIGNALS_Signal uint16;




// Signals' ID
// commonly used
#define HestiaSIGNALS_OK 0
#define HestiaSIGNALS_BAD_EXEC 1
#define HestiaSIGNALS_BAD_BUSY 2
#define HestiaSIGNALS_BAD_DESCRIPTOR 3
#define HestiaSIGNALS_BAD_EXCHANGE 4
#define HestiaSIGNALS_BAD_MOUNT 5
#define HestiaSIGNALS_BAD_PIPE 6
#define HestiaSIGNALS_BAD_REQUEST 7
#define HestiaSIGNALS_BAD_STREAM_PIPE 8
#define HestiaSIGNALS_PROCESS_IS_DEAD 9
#define HestiaSIGNALS_CANCELLED 10
#define HestiaSIGNALS_CLEANING_REQUIRED 11
#define HestiaSIGNALS_DEADLOCK 12
#define HestiaSIGNALS_EXPIRED 13
#define HestiaSIGNALS_ILLEGAL_BYTE_SEQUENCE 14
#define HestiaSIGNALS_ILLEGAL_SEEK 15
#define HestiaSIGNALS_INVALID_ARGUMENT 16
#define HestiaSIGNALS_IS_EMPTY 17
#define HestiaSIGNALS_MAXED_EXCHANGE 18
#define HestiaSIGNALS_MAXED_QUOTA 19
#define HestiaSIGNALS_MISSING_LOCK 20
#define HestiaSIGNALS_IS_NOT_EMPTY 21
#define HestiaSIGNALS_NOT_PERMITTED 22
#define HestiaSIGNALS_NOT_POSSIBLE 23
#define HestiaSIGNALS_NOT_POSSIBLE_BY_RFKILL 24
#define HestiaSIGNALS_NOT_RECOVERABLE 25
#define HestiaSIGNALS_OUT_OF_RANGE 26
#define HestiaSIGNALS_PERMISSION_DENIED 27
#define HestiaSIGNALS_TIMEOUT 28
#define HestiaSIGNALS_TOO_MANY_READ 29
#define HestiaSIGNALS_TOO_MANY_LOOP 30
#define HestiaSIGNALS_TOO_MANY_REFERENCES 31
#define HestiaSIGNALS_TOO_MANY_LINK 32
#define HestiaSIGNALS_TOO_MANY_OPENED 33
#define HestiaSIGNALS_TRY_AGAIN 34
#define HestiaSIGNALS_UNSUPPORTED 35
#define HestiaSIGNALS_WOULD_BLOCK 36




// lifecycle states
#define HestiaSIGNALS_RESTART 37
#define HestiaSIGNALS_RESUME 38
#define HestiaSIGNALS_SHUTDOWN 39
#define HestiaSIGNALS_SLEEP 40
#define HestiaSIGNALS_STALLED 41
#define HestiaSIGNALS_STANDBY 42
#define HestiaSIGNALS_UNRESPONSIVE 43
#define HestiaSIGNALS_TERMINATE 44
#define HestiaSIGNALS_PROGRESS_SCHEDULED 45
#define HestiaSIGNALS_PROGRESS_ALREADY_EXECUTING 46
#define HestiaSIGNALS_PROGRESS_EXECUTING 47
#define HestiaSIGNALS_PROGRESS_COMPLETED 48
#define HestiaSIGNALS_PROGRESS_UNRESPONSIVE 49
#define HestiaSIGNALS_PROGRESS_TERMINATE 50




// tri-tiers intercommunications
#define HestiaSIGNALS_LV1_NOT_SYNC 51
#define HestiaSIGNALS_LV1_PAUSED 52
#define HestiaSIGNALS_LV1_RESET 53
#define HestiaSIGNALS_LV2_NOT_SYNC 54
#define HestiaSIGNALS_LV2_PAUSED 55
#define HestiaSIGNALS_LV2_RESET 56
#define HestiaSIGNALS_LV3_NOT_SYNC 57
#define HestiaSIGNALS_LV3_PAUSED 58
#define HestiaSIGNALS_LV3_RESET 59




// data (input/output parameters type etc)
#define HestiaSIGNALS_DATA_BAD 60
#define HestiaSIGNALS_DATA_EMPTY 61
#define HestiaSIGNALS_DATA_INVALID 62
#define HestiaSIGNALS_DATA_IS_UNIQUE 63
#define HestiaSIGNALS_DATA_IS_NOT_UNIQUE 64
#define HestiaSIGNALS_DATA_BUSY 65
#define HestiaSIGNALS_DATA_DEAD 66
#define HestiaSIGNALS_DATA_EXISTS 67
#define HestiaSIGNALS_DATA_FAULTY 68
#define HestiaSIGNALS_DATA_MISSING 69
#define HestiaSIGNALS_DATA_OVERFLOW 70
#define HestiaSIGNALS_DATA_POISONED 71
#define HestiaSIGNALS_DATA_REMOVED 72
#define HestiaSIGNALS_DATA_TOO_BIG 73
#define HestiaSIGNALS_DATA_TOO_MANY_OPENED 74
#define HestiaSIGNALS_DATA_TOO_LONG 75
#define HestiaSIGNALS_DATA_MISMATCHED 76
#define HestiaSIGNALS_DATA_IS_NOT_DIRECTORY 77
#define HestiaSIGNALS_DATA_IS_NOT_FILE 78
#define HestiaSIGNALS_DATA_IS_NOT_LINK 79
#define HestiaSIGNALS_DATA_IS_NOT_SOCKET 80
#define HestiaSIGNALS_DATA_REMOTE_CHANGED 81
#define HestiaSIGNALS_DATA_REMOTE_ERROR 82
#define HestiaSIGNALS_DATA_REMOTE_IO 83
#define HestiaSIGNALS_DATA_MISSING_STREAMABLE_RESOURCES 84
#define HestiaSIGNALS_DATA_NOT_STREAMABLE 85




// entity (device file directory object etc)
#define HestiaSIGNALS_ENTITY_BAD 86
#define HestiaSIGNALS_ENTITY_EMPTY 87
#define HestiaSIGNALS_ENTITY_INVALID 88
#define HestiaSIGNALS_ENTITY_IS_UNIQUE 89
#define HestiaSIGNALS_ENTITY_IS_NOT_UNIQUE 90
#define HestiaSIGNALS_ENTITY_BUSY 91
#define HestiaSIGNALS_ENTITY_DEAD 92
#define HestiaSIGNALS_ENTITY_EXISTS 93
#define HestiaSIGNALS_ENTITY_FAULTY 94
#define HestiaSIGNALS_ENTITY_MISSING 95
#define HestiaSIGNALS_ENTITY_MISSING_CHILD 96
#define HestiaSIGNALS_ENTITY_OUT_OF_BUFFER 97
#define HestiaSIGNALS_ENTITY_POISONED 98
#define HestiaSIGNALS_ENTITY_REMOVED 99
#define HestiaSIGNALS_ENTITY_TOO_BIG 100
#define HestiaSIGNALS_ENTITY_TOO_MANY_OPENED 101
#define HestiaSIGNALS_ENTITY_UNATTACHED 102
#define HestiaSIGNALS_ENTITY_MISMATCHED 103
#define HestiaSIGNALS_ENTITY_IS_NOT_DIRECTORY 104
#define HestiaSIGNALS_ENTITY_IS_NOT_FILE 105
#define HestiaSIGNALS_ENTITY_IS_NOT_LINK 106
#define HestiaSIGNALS_ENTITY_IS_NOT_SOCKET 107
#define HestiaSIGNALS_ENTITY_REMOTE_CHANGED 108
#define HestiaSIGNALS_ENTITY_REMOTE_ERROR 109
#define HestiaSIGNALS_ENTITY_REMOTE_IO 110
#define HestiaSIGNALS_ENTITY_MISSING_STREAMABLE_RESOURCES 111
#define HestiaSIGNALS_ENTITY_NOT_STREAMABLE 112
#define HestiaSIGNALS_ENTITY_STREAMABLE 113
#define HestiaSIGNALS_ENTITY_A_TYPEWRITER 114
#define HestiaSIGNALS_ENTITY_NOT_A_TYPEWRITER 115
#define HestiaSIGNALS_ENTITY_BAD_DESCRIPTOR 116
#define HestiaSIGNALS_ENTITY_FILETABLE_OVERFLOW 117




// key (cryptography)
#define HestiaSIGNALS_KEY_BAD 118
#define HestiaSIGNALS_KEY_DESTROYED 119
#define HestiaSIGNALS_KEY_EXPIRED 120
#define HestiaSIGNALS_KEY_MISSING 121
#define HestiaSIGNALS_KEY_REJECTED 122
#define HestiaSIGNALS_KEY_REVOKED 123




// library
#define HestiaSIGNALS_LIBRARY_BAD 124
#define HestiaSIGNALS_LIBRARY_CORRUPTED 125
#define HestiaSIGNALS_LIBRARY_EXEC_FAILED 126
#define HestiaSIGNALS_LIBRARY_MAXED 127
#define HestiaSIGNALS_LIBRARY_MISSING 128




// network
#define HestiaSIGNALS_NETWORK_BAD 129
#define HestiaSIGNALS_NETWORK_BAD_AD 130
#define HestiaSIGNALS_NETWORK_DOWN 131
#define HestiaSIGNALS_NETWORK_NOT_CONNECTED 132
#define HestiaSIGNALS_NETWORK_RESET 133
#define HestiaSIGNALS_NETWORK_RFS 134
#define HestiaSIGNALS_NETWORK_UNREACHABLE 135

#define HestiaSIGNALS_NETWORK_HOST_DOWN 136
#define HestiaSIGNALS_NETWORK_HOST_UNREACHABLE 137
#define HestiaSIGNALS_NETWORK_SOCKET_UNSUPPORTED 138

#define HestiaSIGNALS_NETWORK_ADDRESS_IN_USE 139
#define HestiaSIGNALS_NETWORK_ADDRESS_UNAVAILABLE 140

#define HestiaSIGNALS_NETWORK_CONN_ABORTED 141
#define HestiaSIGNALS_NETWORK_CONN_IS_CONNECTED 142
#define HestiaSIGNALS_NETWORK_CONN_MISSING_DEST_ADDRESS 143
#define HestiaSIGNALS_NETWORK_CONN_MULTIHOP 144
#define HestiaSIGNALS_NETWORK_CONN_NOT_CONNECTED 145
#define HestiaSIGNALS_NETWORK_CONN_REFUSED 146
#define HestiaSIGNALS_NETWORK_CONN_RESET 147

#define HestiaSIGNALS_NETWORK_PAYLOAD_BAD 148
#define HestiaSIGNALS_NETWORK_PAYLOAD_EMPTY 149
#define HestiaSIGNALS_NETWORK_PAYLOAD_MISSING 150
#define HestiaSIGNALS_NETWORK_PAYLOAD_TOO_LONG 151




// protocol
#define HestiaSIGNALS_PROTOCOL_ADDRESS_UNSUPPORTED 152
#define HestiaSIGNALS_PROTOCOL_BAD 153
#define HestiaSIGNALS_PROTOCOL_FAMILY_UNSUPPORTED 154
#define HestiaSIGNALS_PROTOCOL_MISSING 155
#define HestiaSIGNALS_PROTOCOL_INVALID 156
#define HestiaSIGNALS_PROTOCOL_FAULTY 157
#define HestiaSIGNALS_PROTOCOL_EMPTY 158
#define HestiaSIGNALS_PROTOCOL_UNSUPPORTED 159




// system (e.g. os interactable system)
#define HestiaSIGNALS_SYSTEM_BAD_IO 160
#define HestiaSIGNALS_SYSTEM_DEVICE_CROSS_LINK 161
#define HestiaSIGNALS_SYSTEM_INTERRUPT_CALL 162
#define HestiaSIGNALS_SYSTEM_INVALID 163
#define HestiaSIGNALS_SYSTEM_MISSING_BLOCK_DEVICE 164
#define HestiaSIGNALS_SYSTEM_MISSING_DEVICE 165
#define HestiaSIGNALS_SYSTEM_MISSING_IO 166
#define HestiaSIGNALS_SYSTEM_MISSING_PROCESS 167
#define HestiaSIGNALS_SYSTEM_OUT_OF_DOMAIN 168
#define HestiaSIGNALS_SYSTEM_OUT_OF_MEMORY 169
#define HestiaSIGNALS_SYSTEM_OUT_OF_SPACE 170
#define HestiaSIGNALS_SYSTEM_READ_ONLY_FILESYSTEM 171




// user
#define HestiaSIGNALS_USER_ACCESS_BANNED 172
#define HestiaSIGNALS_USER_ACCESS_LOCKED 173
#define HestiaSIGNALS_USER_ACCESS_NOT_VERIFIED 174
#define HestiaSIGNALS_USER_ACCESS_BAD 175
#define HestiaSIGNALS_USER_ACCESS_REJECTED 176
#define HestiaSIGNALS_USER_ACCESS_REVOKED 177
#define HestiaSIGNALS_USER_ACCESS_EXISTS 178
#define HestiaSIGNALS_USER_ACCESS_EMPTY 179
#define HestiaSIGNALS_USER_ACCESS_MISSING 180
#define HestiaSIGNALS_USER_ACCESS_INVALID 181
#define HestiaSIGNALS_USER_ACCESS_EXPIRED 182
#define HestiaSIGNALS_USER_ACCESS_MISMATCHED 183

#define HestiaSIGNALS_USER_MFA_BANNED 184
#define HestiaSIGNALS_USER_MFA_LOCKED 185
#define HestiaSIGNALS_USER_MFA_NOT_VERIFIED 186
#define HestiaSIGNALS_USER_MFA_BAD 187
#define HestiaSIGNALS_USER_MFA_REJECTED 188
#define HestiaSIGNALS_USER_MFA_REVOKED 189
#define HestiaSIGNALS_USER_MFA_EXISTS 190
#define HestiaSIGNALS_USER_MFA_EMPTY 191
#define HestiaSIGNALS_USER_MFA_MISSING 192
#define HestiaSIGNALS_USER_MFA_INVALID 193
#define HestiaSIGNALS_USER_MFA_EXPIRED 194
#define HestiaSIGNALS_USER_MFA_MISMATCHED 195

#define HestiaSIGNALS_USER_ID_EXISTS 196
#define HestiaSIGNALS_USER_ID_BANNED 197
#define HestiaSIGNALS_USER_ID_BAD 198
#define HestiaSIGNALS_USER_ID_LOCKED 199
#define HestiaSIGNALS_USER_ID_NOT_VERIFIED 200
#define HestiaSIGNALS_USER_ID_EMPTY 201
#define HestiaSIGNALS_USER_ID_MISSING 202
#define HestiaSIGNALS_USER_ID_INVALID 203
#define HestiaSIGNALS_USER_ID_EXPIRED 204
#define HestiaSIGNALS_USER_ID_MISMATCHED 205
#define HestiaSIGNALS_USER_ID_DELETED 206

#define HestiaSIGNALS_USER_PASSWORD_EXISTS 207
#define HestiaSIGNALS_USER_PASSWORD_BANNED 208
#define HestiaSIGNALS_USER_PASSWORD_BAD 209
#define HestiaSIGNALS_USER_PASSWORD_REJECTED 210
#define HestiaSIGNALS_USER_PASSWORD_REVOKED 211
#define HestiaSIGNALS_USER_PASSWORD_EMPTY 212
#define HestiaSIGNALS_USER_PASSWORD_MISSING 213
#define HestiaSIGNALS_USER_PASSWORD_INVALID 214
#define HestiaSIGNALS_USER_PASSWORD_EXPIRED 215
#define HestiaSIGNALS_USER_PASSWORD_MISMATCHED 216

#define HestiaSIGNALS_USER_KEY_EXISTS 217
#define HestiaSIGNALS_USER_KEY_BANNED 218
#define HestiaSIGNALS_USER_KEY_BAD 219
#define HestiaSIGNALS_USER_KEY_REJECTED 220
#define HestiaSIGNALS_USER_KEY_REVOKED 221
#define HestiaSIGNALS_USER_KEY_EMPTY 222
#define HestiaSIGNALS_USER_KEY_MISSING 223
#define HestiaSIGNALS_USER_KEY_INVALID 224
#define HestiaSIGNALS_USER_KEY_EXPIRED 225
#define HestiaSIGNALS_USER_KEY_MISMATCHED 226


#endif // HestiaSIGNALS_CODES
