# Copyright 2025 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
# Copyright 2024 (Holloway) Chew, Kean Ho <hello@hollowaykeanho.com>
# Copyright 2023 (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
#
#
# Licensed under (Holloway) Chew, Kean Ho's Liberal License (the 'License').
# You must comply with the license to use the content. Get the License at:
#
# https://doi.org/10.5281/zenodo.13770769
#
# You MUST ensure any interaction with the content STRICTLY COMPLIES with
# the permissions and limitations set forth in the license.


# WARNING: This file is AUTO-GENERATED! DO NOT EDIT!
# WARNING: Consult Copyright owners or documentations.

type
  Signal*: uint16




# Signals' ID
const
  # commonly used
  HestiaSIGNALS_OK*: Signal = 0
  HestiaSIGNALS_BAD_EXEC*: Signal = 1
  HestiaSIGNALS_BAD_BUSY*: Signal = 2
  HestiaSIGNALS_BAD_DESCRIPTOR*: Signal = 3
  HestiaSIGNALS_BAD_EXCHANGE*: Signal = 4
  HestiaSIGNALS_BAD_MOUNT*: Signal = 5
  HestiaSIGNALS_BAD_PIPE*: Signal = 6
  HestiaSIGNALS_BAD_REQUEST*: Signal = 7
  HestiaSIGNALS_BAD_STREAM_PIPE*: Signal = 8
  HestiaSIGNALS_PROCESS_IS_DEAD*: Signal = 9
  HestiaSIGNALS_CANCELLED*: Signal = 10
  HestiaSIGNALS_CLEANING_REQUIRED*: Signal = 11
  HestiaSIGNALS_DEADLOCK*: Signal = 12
  HestiaSIGNALS_EXPIRED*: Signal = 13
  HestiaSIGNALS_ILLEGAL_BYTE_SEQUENCE*: Signal = 14
  HestiaSIGNALS_ILLEGAL_SEEK*: Signal = 15
  HestiaSIGNALS_INVALID_ARGUMENT*: Signal = 16
  HestiaSIGNALS_IS_EMPTY*: Signal = 17
  HestiaSIGNALS_MAXED_EXCHANGE*: Signal = 18
  HestiaSIGNALS_MAXED_QUOTA*: Signal = 19
  HestiaSIGNALS_MISSING_LOCK*: Signal = 20
  HestiaSIGNALS_IS_NOT_EMPTY*: Signal = 21
  HestiaSIGNALS_NOT_PERMITTED*: Signal = 22
  HestiaSIGNALS_NOT_POSSIBLE*: Signal = 23
  HestiaSIGNALS_NOT_POSSIBLE_BY_RFKILL*: Signal = 24
  HestiaSIGNALS_NOT_RECOVERABLE*: Signal = 25
  HestiaSIGNALS_OUT_OF_RANGE*: Signal = 26
  HestiaSIGNALS_PERMISSION_DENIED*: Signal = 27
  HestiaSIGNALS_TIMEOUT*: Signal = 28
  HestiaSIGNALS_TOO_MANY_READ*: Signal = 29
  HestiaSIGNALS_TOO_MANY_LOOP*: Signal = 30
  HestiaSIGNALS_TOO_MANY_REFERENCES*: Signal = 31
  HestiaSIGNALS_TOO_MANY_LINK*: Signal = 32
  HestiaSIGNALS_TOO_MANY_OPENED*: Signal = 33
  HestiaSIGNALS_TRY_AGAIN*: Signal = 34
  HestiaSIGNALS_UNSUPPORTED*: Signal = 35
  HestiaSIGNALS_WOULD_BLOCK*: Signal = 36




  # lifecycle states
  HestiaSIGNALS_RESTART*: Signal = 37
  HestiaSIGNALS_RESUME*: Signal = 38
  HestiaSIGNALS_SHUTDOWN*: Signal = 39
  HestiaSIGNALS_SLEEP*: Signal = 40
  HestiaSIGNALS_STALLED*: Signal = 41
  HestiaSIGNALS_STANDBY*: Signal = 42
  HestiaSIGNALS_UNRESPONSIVE*: Signal = 43
  HestiaSIGNALS_TERMINATE*: Signal = 44
  HestiaSIGNALS_PROGRESS_SCHEDULED*: Signal = 45
  HestiaSIGNALS_PROGRESS_ALREADY_EXECUTING*: Signal = 46
  HestiaSIGNALS_PROGRESS_EXECUTING*: Signal = 47
  HestiaSIGNALS_PROGRESS_COMPLETED*: Signal = 48
  HestiaSIGNALS_PROGRESS_UNRESPONSIVE*: Signal = 49
  HestiaSIGNALS_PROGRESS_TERMINATE*: Signal = 50




  # tri-tiers intercommunications
  HestiaSIGNALS_LV1_NOT_SYNC*: Signal = 51
  HestiaSIGNALS_LV1_PAUSED*: Signal = 52
  HestiaSIGNALS_LV1_RESET*: Signal = 53
  HestiaSIGNALS_LV2_NOT_SYNC*: Signal = 54
  HestiaSIGNALS_LV2_PAUSED*: Signal = 55
  HestiaSIGNALS_LV2_RESET*: Signal = 56
  HestiaSIGNALS_LV3_NOT_SYNC*: Signal = 57
  HestiaSIGNALS_LV3_PAUSED*: Signal = 58
  HestiaSIGNALS_LV3_RESET*: Signal = 59




  # data (input/output parameters type etc)
  HestiaSIGNALS_DATA_BAD*: Signal = 60
  HestiaSIGNALS_DATA_EMPTY*: Signal = 61
  HestiaSIGNALS_DATA_INVALID*: Signal = 62
  HestiaSIGNALS_DATA_IS_UNIQUE*: Signal = 63
  HestiaSIGNALS_DATA_IS_NOT_UNIQUE*: Signal = 64
  HestiaSIGNALS_DATA_BUSY*: Signal = 65
  HestiaSIGNALS_DATA_DEAD*: Signal = 66
  HestiaSIGNALS_DATA_EXISTS*: Signal = 67
  HestiaSIGNALS_DATA_FAULTY*: Signal = 68
  HestiaSIGNALS_DATA_MISSING*: Signal = 69
  HestiaSIGNALS_DATA_OVERFLOW*: Signal = 70
  HestiaSIGNALS_DATA_POISONED*: Signal = 71
  HestiaSIGNALS_DATA_REMOVED*: Signal = 72
  HestiaSIGNALS_DATA_TOO_BIG*: Signal = 73
  HestiaSIGNALS_DATA_TOO_MANY_OPENED*: Signal = 74
  HestiaSIGNALS_DATA_TOO_LONG*: Signal = 75
  HestiaSIGNALS_DATA_MISMATCHED*: Signal = 76
  HestiaSIGNALS_DATA_IS_NOT_DIRECTORY*: Signal = 77
  HestiaSIGNALS_DATA_IS_NOT_FILE*: Signal = 78
  HestiaSIGNALS_DATA_IS_NOT_LINK*: Signal = 79
  HestiaSIGNALS_DATA_IS_NOT_SOCKET*: Signal = 80
  HestiaSIGNALS_DATA_REMOTE_CHANGED*: Signal = 81
  HestiaSIGNALS_DATA_REMOTE_ERROR*: Signal = 82
  HestiaSIGNALS_DATA_REMOTE_IO*: Signal = 83
  HestiaSIGNALS_DATA_MISSING_STREAMABLE_RESOURCES*: Signal = 84
  HestiaSIGNALS_DATA_NOT_STREAMABLE*: Signal = 85




  # entity (device file directory object etc)
  HestiaSIGNALS_ENTITY_BAD*: Signal = 86
  HestiaSIGNALS_ENTITY_EMPTY*: Signal = 87
  HestiaSIGNALS_ENTITY_INVALID*: Signal = 88
  HestiaSIGNALS_ENTITY_IS_UNIQUE*: Signal = 89
  HestiaSIGNALS_ENTITY_IS_NOT_UNIQUE*: Signal = 90
  HestiaSIGNALS_ENTITY_BUSY*: Signal = 91
  HestiaSIGNALS_ENTITY_DEAD*: Signal = 92
  HestiaSIGNALS_ENTITY_EXISTS*: Signal = 93
  HestiaSIGNALS_ENTITY_FAULTY*: Signal = 94
  HestiaSIGNALS_ENTITY_MISSING*: Signal = 95
  HestiaSIGNALS_ENTITY_MISSING_CHILD*: Signal = 96
  HestiaSIGNALS_ENTITY_OUT_OF_BUFFER*: Signal = 97
  HestiaSIGNALS_ENTITY_POISONED*: Signal = 98
  HestiaSIGNALS_ENTITY_REMOVED*: Signal = 99
  HestiaSIGNALS_ENTITY_TOO_BIG*: Signal = 100
  HestiaSIGNALS_ENTITY_TOO_MANY_OPENED*: Signal = 101
  HestiaSIGNALS_ENTITY_UNATTACHED*: Signal = 102
  HestiaSIGNALS_ENTITY_MISMATCHED*: Signal = 103
  HestiaSIGNALS_ENTITY_IS_NOT_DIRECTORY*: Signal = 104
  HestiaSIGNALS_ENTITY_IS_NOT_FILE*: Signal = 105
  HestiaSIGNALS_ENTITY_IS_NOT_LINK*: Signal = 106
  HestiaSIGNALS_ENTITY_IS_NOT_SOCKET*: Signal = 107
  HestiaSIGNALS_ENTITY_REMOTE_CHANGED*: Signal = 108
  HestiaSIGNALS_ENTITY_REMOTE_ERROR*: Signal = 109
  HestiaSIGNALS_ENTITY_REMOTE_IO*: Signal = 110
  HestiaSIGNALS_ENTITY_MISSING_STREAMABLE_RESOURCES*: Signal = 111
  HestiaSIGNALS_ENTITY_NOT_STREAMABLE*: Signal = 112
  HestiaSIGNALS_ENTITY_STREAMABLE*: Signal = 113
  HestiaSIGNALS_ENTITY_A_TYPEWRITER*: Signal = 114
  HestiaSIGNALS_ENTITY_NOT_A_TYPEWRITER*: Signal = 115
  HestiaSIGNALS_ENTITY_BAD_DESCRIPTOR*: Signal = 116
  HestiaSIGNALS_ENTITY_FILETABLE_OVERFLOW*: Signal = 117




  # key (cryptography)
  HestiaSIGNALS_KEY_BAD*: Signal = 118
  HestiaSIGNALS_KEY_DESTROYED*: Signal = 119
  HestiaSIGNALS_KEY_EXPIRED*: Signal = 120
  HestiaSIGNALS_KEY_MISSING*: Signal = 121
  HestiaSIGNALS_KEY_REJECTED*: Signal = 122
  HestiaSIGNALS_KEY_REVOKED*: Signal = 123




  # library
  HestiaSIGNALS_LIBRARY_BAD*: Signal = 124
  HestiaSIGNALS_LIBRARY_CORRUPTED*: Signal = 125
  HestiaSIGNALS_LIBRARY_EXEC_FAILED*: Signal = 126
  HestiaSIGNALS_LIBRARY_MAXED*: Signal = 127
  HestiaSIGNALS_LIBRARY_MISSING*: Signal = 128




  # network
  HestiaSIGNALS_NETWORK_BAD*: Signal = 129
  HestiaSIGNALS_NETWORK_BAD_AD*: Signal = 130
  HestiaSIGNALS_NETWORK_DOWN*: Signal = 131
  HestiaSIGNALS_NETWORK_NOT_CONNECTED*: Signal = 132
  HestiaSIGNALS_NETWORK_RESET*: Signal = 133
  HestiaSIGNALS_NETWORK_RFS*: Signal = 134
  HestiaSIGNALS_NETWORK_UNREACHABLE*: Signal = 135

  HestiaSIGNALS_NETWORK_HOST_DOWN*: Signal = 136
  HestiaSIGNALS_NETWORK_HOST_UNREACHABLE*: Signal = 137
  HestiaSIGNALS_NETWORK_SOCKET_UNSUPPORTED*: Signal = 138

  HestiaSIGNALS_NETWORK_ADDRESS_IN_USE*: Signal = 139
  HestiaSIGNALS_NETWORK_ADDRESS_UNAVAILABLE*: Signal = 140

  HestiaSIGNALS_NETWORK_CONN_ABORTED*: Signal = 141
  HestiaSIGNALS_NETWORK_CONN_IS_CONNECTED*: Signal = 142
  HestiaSIGNALS_NETWORK_CONN_MISSING_DEST_ADDRESS*: Signal = 143
  HestiaSIGNALS_NETWORK_CONN_MULTIHOP*: Signal = 144
  HestiaSIGNALS_NETWORK_CONN_NOT_CONNECTED*: Signal = 145
  HestiaSIGNALS_NETWORK_CONN_REFUSED*: Signal = 146
  HestiaSIGNALS_NETWORK_CONN_RESET*: Signal = 147

  HestiaSIGNALS_NETWORK_PAYLOAD_BAD*: Signal = 148
  HestiaSIGNALS_NETWORK_PAYLOAD_EMPTY*: Signal = 149
  HestiaSIGNALS_NETWORK_PAYLOAD_MISSING*: Signal = 150
  HestiaSIGNALS_NETWORK_PAYLOAD_TOO_LONG*: Signal = 151




  # protocol
  HestiaSIGNALS_PROTOCOL_ADDRESS_UNSUPPORTED*: Signal = 152
  HestiaSIGNALS_PROTOCOL_BAD*: Signal = 153
  HestiaSIGNALS_PROTOCOL_FAMILY_UNSUPPORTED*: Signal = 154
  HestiaSIGNALS_PROTOCOL_MISSING*: Signal = 155
  HestiaSIGNALS_PROTOCOL_INVALID*: Signal = 156
  HestiaSIGNALS_PROTOCOL_FAULTY*: Signal = 157
  HestiaSIGNALS_PROTOCOL_EMPTY*: Signal = 158
  HestiaSIGNALS_PROTOCOL_UNSUPPORTED*: Signal = 159




  # system (e.g. os interactable system)
  HestiaSIGNALS_SYSTEM_BAD_IO*: Signal = 160
  HestiaSIGNALS_SYSTEM_DEVICE_CROSS_LINK*: Signal = 161
  HestiaSIGNALS_SYSTEM_INTERRUPT_CALL*: Signal = 162
  HestiaSIGNALS_SYSTEM_INVALID*: Signal = 163
  HestiaSIGNALS_SYSTEM_MISSING_BLOCK_DEVICE*: Signal = 164
  HestiaSIGNALS_SYSTEM_MISSING_DEVICE*: Signal = 165
  HestiaSIGNALS_SYSTEM_MISSING_IO*: Signal = 166
  HestiaSIGNALS_SYSTEM_MISSING_PROCESS*: Signal = 167
  HestiaSIGNALS_SYSTEM_OUT_OF_DOMAIN*: Signal = 168
  HestiaSIGNALS_SYSTEM_OUT_OF_MEMORY*: Signal = 169
  HestiaSIGNALS_SYSTEM_OUT_OF_SPACE*: Signal = 170
  HestiaSIGNALS_SYSTEM_READ_ONLY_FILESYSTEM*: Signal = 171




  # user
  HestiaSIGNALS_USER_ACCESS_BANNED*: Signal = 172
  HestiaSIGNALS_USER_ACCESS_LOCKED*: Signal = 173
  HestiaSIGNALS_USER_ACCESS_NOT_VERIFIED*: Signal = 174
  HestiaSIGNALS_USER_ACCESS_BAD*: Signal = 175
  HestiaSIGNALS_USER_ACCESS_REJECTED*: Signal = 176
  HestiaSIGNALS_USER_ACCESS_REVOKED*: Signal = 177
  HestiaSIGNALS_USER_ACCESS_EXISTS*: Signal = 178
  HestiaSIGNALS_USER_ACCESS_EMPTY*: Signal = 179
  HestiaSIGNALS_USER_ACCESS_MISSING*: Signal = 180
  HestiaSIGNALS_USER_ACCESS_INVALID*: Signal = 181
  HestiaSIGNALS_USER_ACCESS_EXPIRED*: Signal = 182
  HestiaSIGNALS_USER_ACCESS_MISMATCHED*: Signal = 183

  HestiaSIGNALS_USER_MFA_BANNED*: Signal = 184
  HestiaSIGNALS_USER_MFA_LOCKED*: Signal = 185
  HestiaSIGNALS_USER_MFA_NOT_VERIFIED*: Signal = 186
  HestiaSIGNALS_USER_MFA_BAD*: Signal = 187
  HestiaSIGNALS_USER_MFA_REJECTED*: Signal = 188
  HestiaSIGNALS_USER_MFA_REVOKED*: Signal = 189
  HestiaSIGNALS_USER_MFA_EXISTS*: Signal = 190
  HestiaSIGNALS_USER_MFA_EMPTY*: Signal = 191
  HestiaSIGNALS_USER_MFA_MISSING*: Signal = 192
  HestiaSIGNALS_USER_MFA_INVALID*: Signal = 193
  HestiaSIGNALS_USER_MFA_EXPIRED*: Signal = 194
  HestiaSIGNALS_USER_MFA_MISMATCHED*: Signal = 195

  HestiaSIGNALS_USER_ID_EXISTS*: Signal = 196
  HestiaSIGNALS_USER_ID_BANNED*: Signal = 197
  HestiaSIGNALS_USER_ID_BAD*: Signal = 198
  HestiaSIGNALS_USER_ID_LOCKED*: Signal = 199
  HestiaSIGNALS_USER_ID_NOT_VERIFIED*: Signal = 200
  HestiaSIGNALS_USER_ID_EMPTY*: Signal = 201
  HestiaSIGNALS_USER_ID_MISSING*: Signal = 202
  HestiaSIGNALS_USER_ID_INVALID*: Signal = 203
  HestiaSIGNALS_USER_ID_EXPIRED*: Signal = 204
  HestiaSIGNALS_USER_ID_MISMATCHED*: Signal = 205
  HestiaSIGNALS_USER_ID_DELETED*: Signal = 206

  HestiaSIGNALS_USER_PASSWORD_EXISTS*: Signal = 207
  HestiaSIGNALS_USER_PASSWORD_BANNED*: Signal = 208
  HestiaSIGNALS_USER_PASSWORD_BAD*: Signal = 209
  HestiaSIGNALS_USER_PASSWORD_REJECTED*: Signal = 210
  HestiaSIGNALS_USER_PASSWORD_REVOKED*: Signal = 211
  HestiaSIGNALS_USER_PASSWORD_EMPTY*: Signal = 212
  HestiaSIGNALS_USER_PASSWORD_MISSING*: Signal = 213
  HestiaSIGNALS_USER_PASSWORD_INVALID*: Signal = 214
  HestiaSIGNALS_USER_PASSWORD_EXPIRED*: Signal = 215
  HestiaSIGNALS_USER_PASSWORD_MISMATCHED*: Signal = 216

  HestiaSIGNALS_USER_KEY_EXISTS*: Signal = 217
  HestiaSIGNALS_USER_KEY_BANNED*: Signal = 218
  HestiaSIGNALS_USER_KEY_BAD*: Signal = 219
  HestiaSIGNALS_USER_KEY_REJECTED*: Signal = 220
  HestiaSIGNALS_USER_KEY_REVOKED*: Signal = 221
  HestiaSIGNALS_USER_KEY_EMPTY*: Signal = 222
  HestiaSIGNALS_USER_KEY_MISSING*: Signal = 223
  HestiaSIGNALS_USER_KEY_INVALID*: Signal = 224
  HestiaSIGNALS_USER_KEY_EXPIRED*: Signal = 225
  HestiaSIGNALS_USER_KEY_MISMATCHED*: Signal = 226
